dist: trusty # uses trusty environment
sudo: false # when on trusty, uses Docker containers for speed
language: node_js
node_js:
  - node # uses most recent stable node version
install:
  - npm i -g npm@6
  - npm ci # faster, goes only from package-lock
